version: "3.8"

networks:
  browser-game-network:
    name: doc-container-node-ts
    driver: bridge

services:
  node-app:
    build:
      context: .
      dockerfile: docker/node-js-22/Dockerfile
    container_name: server-doc-container-node-ts
    working_dir: /var/www/doc-container-node-ts  # Указываем рабочую директорию внутри контейнера
    ports:
      - "9003:9003" # Пробрасываем порт для работы сервера
      - "9229:9229" # Пробрасываем порт для отладки Node.js
    volumes:
      - ./public:/var/www/doc-container-node-ts  # Монтируем локальную папку public в контейнер
    networks:
      - browser-game-network
    command: npm run dev
    # command: npm run start # Запускаем сервер через npm start

    # ---
    # environment — это ключ, который используется в Docker Compose для задания
    # переменных окружения внутри контейнера.
    # Пример использования:
    # const nodeEnv = process.env.NODE_ENV;  // "production"
    # const databaseUrl = process.env.DATABASE_URL;
    # ---
    #environment:
    #  - NODE_ENV=production //development,production
    #  - DATABASE_URL=mongodb://mongo:27017/mydb
    # ---
